In [ ]:
import numpy as np
import pandas as pd

In [ ]:
dataset=pd.read_csv('/content/diabetes - diabetes.csv')
dataset

Glucose  BloodPressure   BMI  DiabetesPedigreeFunction  Age  Outcome
0         89           66.0  28.1                     0.167   21        0
1        137           40.0  43.1                     2.288   33        1
2         78           50.0  31.0                     0.248   26        1
3        197           70.0  30.5                     0.158   53        1
4        110           92.0  37.6                     0.191   30        0
..       ...            ...   ...                       ...  ...      ...
568      111           84.0  46.8                     0.925   45        1
569      112           78.0  39.4                     0.175   24        0
570      132           80.0  34.4                     0.402   44        1
571       82           52.0  28.5                     1.699   25        0
572      123           72.0  33.6                     0.733   34        0

[573 rows x 6 columns]

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 573 entries, 0 to 572
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Glucose                   573 non-null    int64  
 1   BloodPressure             561 non-null    float64
 2   BMI                       570 non-null    float64
 3   DiabetesPedigreeFunction  573 non-null    float64
 4   Age                       573 non-null    int64  
 5   Outcome                   573 non-null    int64  
dtypes: float64(3), int64(3)
memory usage: 27.0 KB


In [ ]:
dataset['BloodPressure'].fillna(dataset['BloodPressure'].mean(),inplace=True)
dataset['BMI'].fillna(dataset['BMI'].mean(),inplace=True)


In [ ]:
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values
x,y

(array([[ 89.   ,  66.   ,  28.1  ,   0.167,  21.   ],
        [137.   ,  40.   ,  43.1  ,   2.288,  33.   ],
        [ 78.   ,  50.   ,  31.   ,   0.248,  26.   ],
        ...,
        [132.   ,  80.   ,  34.4  ,   0.402,  44.   ],
        [ 82.   ,  52.   ,  28.5  ,   1.699,  25.   ],
        [123.   ,  72.   ,  33.6  ,   0.733,  34.   ]]),
 array([0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
        0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
        0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
        1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier()
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [ ]:
y_pred=classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 0]
 [0 1]
 [0 1]
 [1 1]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 0]
 [0 0]
 [0 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]

In [ ]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1_score=f1_score(y_test,y_pred)

print("f1_score",f1_score)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)

f1_score 0.5625
Accuracy: 0.7083333333333334
Precision: 0.6136363636363636
Recall: 0.5192307692307693


In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)


array([[75, 17],
       [25, 27]])